### ISSUE TITLE
Create a namespaced CRD format for the configuration

### ISSUE THREAD

**Issue by wstrange** [ForgeRock/secret-agent#1]
The configuration can eventually be migrated to a CRD. Suggest using one namespace per configuration file.

Something like:
```
kind: SecretConfiguration
apiVersion: forgerock.io/v1beta1
metadata:
  name: my-secrets
  namespace: prod
spec:
  secrets: [...]
```
