### ISSUE TITLE
Keys in secret are getting double base64 encoded

### ISSUE THREAD

**Issue by jrcast** [ForgeRock/secret-agent#13]
Take a look at `username`: `WVcxaFpHMXBiZz09` -> `YW1hZG1pbg==` -> `amadmin`

```
apiVersion: v1
Metadata:
  name: am-runtime
  namespace: default
data:
  keypass: WkhodWNGSjVaR3BaU0hwRVQyOHdUQT09
  username: WVcxaFpHMXBiZz09
kind: Secret

```

Steps to reproduce: 
1. start minikube
1.  `make install`
1. `make run`
1. `kubectl create config/samples`
1. see generated secrets
