### ISSUE TITLE
should be able to handle out-of-order self-references in secrets

### ISSUE THREAD

**Issue by jrcast** [ForgeRock/secret-agent#148]
Secret agent should be able to handle out-of-order self-references. Currently, the `secret-agent` falls into an infinite loop if a key references another key form the same secret before it is defined in the `SAC`.

for example: 
```yaml
  - name: ds
    keys:
    - name: keystore
      # Java Keystore type
      type: keytool
      spec:
        storeType: pkcs12
        storePassPath: ds/keystore.pin # <<< Reference keystore.pin before it has been defined
        keyPassPath: ds/keystore.pin  # <<< Reference keystore.pin before it has been defined
        keytoolAliases:
          - name: configstorepwd
            # import a password/passhphrase
            cmd: importpassword
            sourcePath: "am-passwords/.storepass"
    - name: keystore.pin # <<<<<<  keystore.pin  defined here
      type: password
      spec:
        length: 32
      # keystore used by DS
```
