### ISSUE TITLE
README error in cloud backup naming convention example

### ISSUE THREAD

**Issue by tribunzio** [ForgeRock/secret-agent#215]
README error in cloud backup naming convention example.  This is just a documentation error.
After the SAC example
```
apiVersion: secret-agent.secrets.forgerock.io/v1alpha1
kind: SecretAgentConfiguration
metadata:
  name: forgerock-sac
  namespace: dev
spec:
  appConfig:
    secretsManagerPrefix: "devCluster"
    awsRegion: us-east-1
    secretsManager: AWS
  secrets:
  - name: ds-passwords
    keys:
      - name: dirmanager.pw
        type: password
```
there is a mistake: 
The secret generated by the this SAC would be stored as `devCluster-dev-ds-passwords-dirmanager-pw` in the AWS Secret Manager. 

This should instead read :
The secret generated by the this SAC would be stored as `devCluster-ds-passwords-dirmanager-pw` in the AWS Secret Manager. 

because namespace(dev) is not used if secretsManagerPrefix (devCluster) is specified.
