### ISSUE TITLE
Secret Agent should support jceks keystore type

### ISSUE THREAD

**Issue by wstrange** [ForgeRock/secret-agent#43]
Trying to replicate what this command does:
```genRSA () {
    echo "[Keystore ${KEYSTORE}] Generating RSA keypair:${1} key size:${2}"
    keytoolgen -genkeypair -alias ${1} -dname "CN=${1},$DN" -keyalg RSA -keysize ${2} -sigalg SHA256WITHRSA --validity ${VALIDITY}
}
```
Here is my sac config:

```
  # AM secret files that get mounted
  - name: am-passwords
    keys:
    - name: .keypass
      type: password
      length: 32
    - name: .storepass
      type: password
      length: 32

  # The default AM keystore. Contains base keys for SAML/ OIDC signing / encryption, etc
  - name: am-keystore
    keys:
    - name: keystore.jceks
      type: jceks
      storePassPath: ["am-passwords", ".storepass"]
      keyPassPath: ["am-passwords", ".keypass"]
      keystoreAliases:
      - alias: rsajwtsigningkey
        type: keyPair
        algorithm: SHA256WithRSA
        commonName: rsajwtsigningkey,o=forgerock
        selfSigned: true
```

result is an empty 0 byte keystore.jceks

I also need a way to specify the validity of a self signed keypair
