### ISSUE TITLE
AliasMgr `genseckey`

### ISSUE THREAD

**Issue by maxres-fr** [ForgeRock/secret-agent#79]
add aliasmanager for the geseckey for the jceks keystore types.
This currently is unimplemented in master.

```
          storePassPath: am-passwords/.storepass
          keyPassPath: am-passwords/.keypass
          keytoolAliases:
            - name: hmacsigningtest
              cmd: genseckey
              args: ["-keyalg", "HMacSHA512", "-keysize", "512"]
```
